### PR TITLE
Fix test data path in yolo_e2e

### PR DESCRIPTION
**Pull request by VishalX**
Fixed Error: 
```sh
FileNotFoundError: [Errno 2] No such file or directory: 'test\\data\\yolov8n.onnx'
```
while running `python yolo_e2e.py`

### CODE REVIEW

**Comment by wejoncy** [comment]
Hi, @VishalX  
Thanks for your contribution.

You can run from the base dir and "python tutorials/yolo_e2e.py" can resolve it.

**Comment by edgchen1** [comment]
could we make it independent of the current working directory? e.g., could set `script_dir = Path(__file__).parent` and use paths relative to it.

**Comment by wenbingl** [comment]
@wejoncy , may you help to merge this PR?

**Comment by wejoncy** [comment]
> **extensions.ci ** Expected — Waiting for status to be reported

`extensions.ci Expected — Waiting for status to be reported` stops the merge.  I am trying it mannully

**Comment by wenbingl** [comment]
I just did a forcedly merge to avoid running pipeline back and forth after other PR merged.

**Pull request merged**
